### PR TITLE
2k05t0e-properly-use-aria-control

### PR DESCRIPTION
**Pull request by lakshanx**
FIXES:
- aria-controls attribute must point to IDs of elements in the same document

### CODE REVIEW

**Comment by foria** [comment]
@lakshanx I see you removed aria-controls why?

**Comment by lakshanx** [comment]
Removed in certain places, because:

1. Regarding the use of `aria-controls` on filter tabs:
According to the spec, we use must aria-controls with an ID . But here , it's not used to identify a section of the page, But rather, uses as a dynamic filter with js. 
image


3. It's **not** removed from the product page proper tabs.  But regarding:
src/docs/criticals/product.hbs
Here, it's only removed on this criticals/product.hbs page on 2nd and 3rd tabs , because it doesn't have the other tabs on this page: 
It is to avoid getting errors. But this page is just to test critical CSS, correct?

image

**Comment by lakshanx** [comment]
@foria resolved the conflicts

**Comment by lakshanx** [comment]
Notes:
re-added the removed two aria-controls back to the  criticals/product.hbs during the merge.

**Pull request merged**
